package com.haulmont.vaadintesttask.models;

public enum Specialization {
    ALLERGIST,
    ANESTHETIST,
    GASTROENTEROLOGIST,
    HEPATOLOGIST,
    GYNECOLOGIST,
    IMMUNOLOGIST,
    CARDIOLOGIST,
    NEUROPATHOLOGIST,
    ONCOLOGIST,
    OTORHINOLARYNGOLOGIST,
    OPHTHALMOLOGIST,
    PEDIATRICIAN,
    PSYCHOTHERAPIST,
    DENTIST,
    THERAPIST,
    TRAUMATOLOGIST,
    SURGEON
}
